packages:
  - app
  - docs
  - lib
  - tools
  - packages/*

catalog:
  "@types/lodash-es": ^4.17.12
  "@types/node": ^22.15.27
  astro: ^5.8.1
  concurrently: ^9.1.2
  lit: ^3.3.0
  lodash-es: ^4.17.21
  tsx: ^4.19.4
