packages:
  - app
  - lib
  - packages/*

catalog:
  "@commander-js/extra-typings": ^12.1.0
  "@open-wc/testing": ^4.0.0
  "@types/node": ^22.7.5
  "@vitest/coverage-v8": ^2.1.2
  "@vitest/ui": ^2.1.2
  clean-package: ^2.2.0
  commander: ^12.1.0
  concurrently: ^9.0.1
  esbuild: ^0.24.0
  esbuild-plugin-minify-html-literals: ^2.0.1
  jsdom: ^25.0.1
  lit: ^3.2.1
  plop: ^4.0.1
  tsc-watch: ^6.2.0
  tslib: ^2.7.0
  tsx: ^4.19.0
  typescript: ^5.6.3
  vitest: ^2.1.2
